### ISSUE TITLE
Kotlin plugin version

### ISSUE THREAD

**Issue by arn3la** [tuantvu/flutter_linkedin_login#19]
Hello guys, 

I have following problem when I am trying to install you plugin, so do you have any idea what to do. Ofc, it is no option for me to put my kotlin version lower.

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'flutter_linkedin_login' is using version 1.1.51.

**Comment by tuantvu** [comment]
@arn3la I tried to just update the ext.kotlin_version but it causes gradle to break. I generated a new plugin and 1.2.71 compiles fine, but alot has changed in how a plugin is generated. I fear, I'm going to have to start from scratch at some point and regenerate the plugin, meanwhile, probably removing the kotlin and swift dependencies, because I feel flutter plugins don't support those languages very smoothly yet. This change will take me longer to address.

**Comment by d3xt3r2909** [comment]
Hello guys,

@tuantvu and @arn3la  I have created library that is clone of this one, just to fix temporarily this problem. @tuantvu  I will delete it immediately after you fix your bug, but I need it right now, and I am hopping that you are not angry. Please note me when you fix this, and I will delete it. 

By the way, excellent library. 

Link of lib https://github.com/d3xt3r2909/flutter_linkedin_signin

**Comment by tuantvu** [comment]
@d3xt3r2909 Strange, I see you only updated the ext.kotlin_version to 1.2.71, but when I tried that, I get a grade error: 

* What went wrong:
A problem occurred configuring project ':flutter_linkedin_login'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

**Comment by tuantvu** [comment]
@d3xt3r2909 Figured it out, you also changed the kotlin version gradle version in the example app. Thanks for showing me the way, I'll update the plugin shortly, hopefully it doesn't break clients using older kotlin gradle version. I still feel I should remove the kotlin dependency at some point.

**Comment by tuantvu** [comment]
@arn3la @d3xt3r2909 Updated the plugin to v2.2.1

**Comment by d3xt3r2909** [comment]
@tuantvu Super, I hope so. 

Can you just add or just copy main functions so that I delete project from my github. 

Best,
Nihad

**Comment by tuantvu** [comment]
Yes, I will look into that issue later. Been hectic days at work and will have more time this weekend
