### ISSUE TITLE
Handling JSON response

### ISSUE THREAD

**Issue by narulakapil** [tuantvu/flutter_linkedin_login#20]
@tuantvu Thanks a lot for your quick response to https://github.com/tuantvu/flutter_linkedin_login/issues/18#event-2017776179. The fix is proper but just a minor issue though. There are two fields in json that should be processed. They are:

1. publicProfileUrl
2. companyLocation in positions

I used the following LinkedIn API Url:
https://api.linkedin.com/v1/people/~:(id,num-connections,picture-url,picture-urls::(original),first-name,last-name,headline,location,industry,summary,specialties,positions,public-profile-url,email-address)?format=json

A sample JSON response that I got from LinkedIn is posted below.
{
"emailAddress"=>"xxxxx.xxxx@gmail.com",
"firstName"=>"Kapil",
"headline"=>"Business",
"id"=>"xdL70zZCeB",
"industry"=>"Information Services",
"lastName"=>"Narula",
"location"=> {
"country"=> {
"code"=>"in"
},
"name"=>"Kanpur, India"
},
"numConnections"=>70,
"positions"=>{
"_total"=>1,
"values"=>[
{
"company"=>{
"name"=>"Narulas Food Products"
},
"id"=>509073958,
"isCurrent"=>true,
"location"=>{
"country"=>{
"code"=>"in",
"name"=>"India"
},
"name"=>"Lucknow Area, India"
},
"startDate"=>{
"month"=>12,
"year"=>2009
},
"summary"=>"I manage the business operations of my family owned enterprise in Lucknow. ",
"title"=>"Managing Partner"
}
]
},
"publicProfileUrl"=>"http://www.linkedin.com/in/kapil-narula-3217191"
}

**Comment by tuantvu** [comment]
@narulakapil added functionality
