### ISSUE TITLE
get and set access token

### ISSUE THREAD

**Issue by kanteliayagnik** [tuantvu/flutter_linkedin_login#24]
getting a PlatformException error in onSignIn: (profile, ex) 

PlatformException(401, access token is not set, null)

**Comment by tuantvu** [comment]
Hi Yagnik. I'm been out of the country and just got back. I'll check on the issue, but if you see my readme, LinkedIn may have discontinued support for the Mobile API, which this plugin uses. I do plan on updating later to use LinkedIn's new OAuth API. Will update you.

**Comment by kanteliayagnik** [comment]
ok. Thank you for the response. I close this issue.
